### ISSUE TITLE
Resourc unavailable?

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#891] opened 2016-10-17 19:17 UTC
I got this when executing volttron-ctl shutdown --platform on one of boards.  I don't know if this is systemic or not.

```
get_configs': 
Traceback (most recent call last):
  File "/home/volttron/volttron/volttron/platform/vip/agent/subsystems/rpc.py", line 168, in method
    return method(*args, **kwargs)
  File "/home/volttron/volttron/volttron/platform/store.py", line 281, in get_configs
    self.vip.rpc.call(identity, "config.initial_update", agent_configs).get(timeout=10.0)
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/home/volttron/volttron/env/local/lib/python2.7/site-packages/gevent/_util_py2.py", line 8, in reraise
    raise type, value, tb
Again: VIP error (11): Resource temporarily unavailable
```

**Comment by schandrika** [comment] 2020-02-24 20:54
Unable to reproduce. Closing for now. Will reopen if issue is seen again

**Closed by schandrika** 2020-02-24 20:54 UTC
